version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4001:4001"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend

