version: "3.9"

services:
  mongo:
    container_name: mongo
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  backend_new:
    container_name: backend_new
    build: ./backend
    ports:
      - "4001:4001"
    restart: always
    environment:
      - NODE_ENV=production
      # - MONGO_URI=mongodb://mongo:27017/mydb   # ربط backend بـ MongoDB
      - MONGO_URI=mongodb+srv://alibenhenia1:3TkEK63GFAfL8ZZf@cluster0.l3xb1ca.mongodb.net/mydatabase?retryWrites=true&w=majority&appName=Cluster0   # ربط backend بـ MongoDB
      - FRONTEND_URL=http://134.209.238.127:4000 # change to vps ip, this used for cors
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: frontend_v2
    build: ./frontend
    ports:
      - "4000:3000"  # الخارجي : الداخلي
    environment:
      - NEXT_PUBLIC_API_URL=http://134.209.238.127:4001   # استخدم IP VPS هنا
    depends_on:
      - backend_new
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
