name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Build & push Docker image
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build and push image
        run: |
          IMAGE=mydockeruser/myapp
          TAG=$(date +%s) # unique tag (or use $GITHUB_SHA)
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      # Deploy on VPS
      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd v1
            docker compose pull
            docker compose up -d
            docker image prune -f   # cleanup old images
          EOF
