name: Deploy to VPS

on:
  push:
    branches:
      - main   # change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd v1
            git pull origin main
            # Rebuild frontend_v2 without cache
            docker compose build --no-cache frontend_v2

            # Rebuild other services (with cache, faster)
            docker compose build

            # Restart everything
            docker compose down
            docker compose up -d
          EOF
