name: Deploy to VPS

on:
  push:
    branches:
      - main   # change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd v1

            # 1️⃣ Reset local repo to match GitHub (discard local changes)
            git fetch origin main
            git reset --hard origin/main
            git clean -fd

            # 2️⃣ Rebuild frontend_v2 without cache
            docker compose build --no-cache frontend_v2

            # 3️⃣ Restart all services (will rebuild any changed service)
            docker compose up -d --build

            # Optional: clean dangling images to save space
            docker image prune -f
          EOF
